version: '3'

services:
  app:
    container_name: fews_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: fews_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - internal

  certbot:
    image: certbot/certbot
    container_name: fews_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - internal

  mysql:
    image: mysql:5.7
    container_name: fews_bb_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fews_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fews_bb_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: fews_bb_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - internal

networks:
  internal:

volumes:
  mysql_data:
